name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq g++ curl libcurl4-openssl-dev
      - name: build and run tests
        run: |
          make tests
      - name: build
        run: |
          make -B
        env:
          CC: gcc
          CXX: g++
          
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq g++ curl libcurl4-openssl-dev
      - name: build and run tests
        run: |
          make tests
      - name: build
        run: |
          make -B
        env:
          CC: clang
          CXX: clang++
          
  build-macos-clang:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          brew install curl 
      - name: build and run tests
        run: |
          make tests
      - name: build
        run: |
          make -B
        env:
          CC: clang
          CXX: clang++
          
  build-freebsd:
    runs-on: macos-latest
    name: FreeBSD LLVM Clang build
    steps:
    - uses: actions/checkout@v2
    - name: Build on FreeBSD
      id: build
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        usesh: true
        prepare: pkg install -y git pkgconf ftp/curl
        run: |
          ls -l /usr/local/include
          ls -l /usr/local/include | grep curl
          ls -l /usr/local/lib
          ls -l /usr/local/lib | grep curl
          pkg-config --cflags --libs libcurl
          pkg-config --cflags libcurl
          pkg-config --libs libcurl
          freebsd-version
          make -B 
